name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
                    
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          #https://docs.github.com/es/developers/apps/building-github-apps/authenticating-with-github-apps#http-based-git-access-by-an-installation
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}